export type OscillatorType = 'sine' | 'square' | 'sawtooth' | 'triangle'

export type SoundConfig = {
  freq: number
  type: OscillatorType
  duration: number
}

export type ThemeItem = {
  id: string
  emoji: string
  label: string
  color: string
  sound: SoundConfig
  audioUrl?: string   // real sound file URL (optional, falls back to oscillator)
  animation: 'bounce' | 'spin' | 'grow' | 'shake' | 'wiggle'
}

export type Slide = {
  id: string
  bg: string
  animatedBg?: string
  title: string
  scene: string // large emoji scene
  description: string
}

export type Theme = {
  id: string
  name: string
  emoji: string
  bg: string
  accent: string
  buttonBg: string
  animatedBg: string   // CSS gradient for animated background
  items: ThemeItem[]
  slides: Slide[]
}

export const themes: Theme[] = [
  {
    id: 'animals',
    name: 'Animals',
    emoji: '🐄',
    bg: 'from-green-300 via-yellow-200 to-green-400',
    accent: 'text-green-700',
    buttonBg: 'bg-green-500',
    animatedBg: 'linear-gradient(135deg, #86efac, #fde68a, #6ee7b7, #fbbf24, #a7f3d0)',
    items: [
      {
        id: 'cow',
        emoji: '🐄',
        label: 'Cow',
        color: '#f0e6c8',
        sound: { freq: 220, type: 'sine', duration: 0.6 },
        audioUrl: '/sounds/cow.wav',
        animation: 'bounce',
      },
      {
        id: 'pig',
        emoji: '🐷',
        label: 'Pig',
        color: '#ffb3c6',
        sound: { freq: 330, type: 'sine', duration: 0.4 },
        audioUrl: '/sounds/pig.wav',
        animation: 'wiggle',
      },
      {
        id: 'chicken',
        emoji: '🐔',
        label: 'Chicken',
        color: '#fff3b0',
        sound: { freq: 440, type: 'triangle', duration: 0.3 },
        audioUrl: '/sounds/chicken.wav',
        animation: 'shake',
      },
      {
        id: 'horse',
        emoji: '🐴',
        label: 'Horse',
        color: '#d4a574',
        sound: { freq: 196, type: 'sine', duration: 0.7 },
        audioUrl: '/sounds/horse.wav',
        animation: 'bounce',
      },
      {
        id: 'sheep',
        emoji: '🐑',
        label: 'Sheep',
        color: '#e8e8e8',
        sound: { freq: 262, type: 'sine', duration: 0.5 },
        audioUrl: '/sounds/sheep.wav',
        animation: 'grow',
      },
      {
        id: 'duck',
        emoji: '🦆',
        label: 'Duck',
        color: '#ffe066',
        sound: { freq: 370, type: 'triangle', duration: 0.35 },
        audioUrl: '/sounds/duck.wav',
        animation: 'wiggle',
      },
      {
        id: 'dog',
        emoji: '🐶',
        label: 'Dog',
        color: '#c8a97e',
        sound: { freq: 294, type: 'sine', duration: 0.4 },
        audioUrl: '/sounds/dog.wav',
        animation: 'bounce',
      },
      {
        id: 'cat',
        emoji: '🐱',
        label: 'Cat',
        color: '#f4b8d1',
        sound: { freq: 392, type: 'sine', duration: 0.45 },
        audioUrl: '/sounds/cat.wav',
        animation: 'spin',
      },
    ],
    slides: [
      {
        id: 'farm1',
        bg: 'from-sky-300 to-green-400',
        animatedBg: 'linear-gradient(135deg, #7dd3fc, #86efac, #6ee7b7, #34d399, #bef264)',
        title: 'The Farm',
        scene: '🌾🐄🌾',
        description: 'A happy cow on the farm!',
      },
      {
        id: 'farm2',
        bg: 'from-yellow-300 to-orange-300',
        animatedBg: 'linear-gradient(135deg, #fde68a, #fdba74, #fbbf24, #fb923c, #fef08a)',
        title: 'Sunny Day',
        scene: '☀️🐓🌻',
        description: 'The rooster greets the sun!',
      },
      {
        id: 'farm3',
        bg: 'from-pink-300 to-red-300',
        animatedBg: 'linear-gradient(135deg, #f9a8d4, #fca5a5, #fb7185, #f472b6, #fda4af)',
        title: 'Pig Pen',
        scene: '🐷🌈🐷',
        description: 'Piggies love to play!',
      },
      {
        id: 'farm4',
        bg: 'from-green-400 to-emerald-500',
        animatedBg: 'linear-gradient(135deg, #4ade80, #34d399, #6ee7b7, #a7f3d0, #86efac)',
        title: 'Meadow',
        scene: '🐑🌿🌸',
        description: 'Fluffy sheep in the meadow!',
      },
    ],
  },
  {
    id: 'space',
    name: 'Space',
    emoji: '🚀',
    bg: 'from-indigo-900 via-purple-800 to-blue-900',
    accent: 'text-yellow-300',
    buttonBg: 'bg-indigo-600',
    animatedBg: 'linear-gradient(135deg, #1e1b4b, #4c1d95, #1e3a8a, #312e81, #0f172a)',
    items: [
      {
        id: 'rocket',
        emoji: '🚀',
        label: 'Rocket',
        color: '#4f46e5',
        sound: { freq: 880, type: 'sawtooth', duration: 0.5 },
        audioUrl: '/sounds/rocket.wav',
        animation: 'grow',
      },
      {
        id: 'star',
        emoji: '⭐',
        label: 'Star',
        color: '#fbbf24',
        sound: { freq: 1046, type: 'sine', duration: 0.3 },
        audioUrl: '/sounds/star.wav',
        animation: 'spin',
      },
      {
        id: 'moon',
        emoji: '🌙',
        label: 'Moon',
        color: '#c4b5fd',
        sound: { freq: 523, type: 'sine', duration: 0.6 },
        audioUrl: '/sounds/moon.wav',
        animation: 'bounce',
      },
      {
        id: 'planet',
        emoji: '🪐',
        label: 'Planet',
        color: '#7c3aed',
        sound: { freq: 349, type: 'sine', duration: 0.7 },
        audioUrl: '/sounds/planet.wav',
        animation: 'spin',
      },
      {
        id: 'alien',
        emoji: '👾',
        label: 'Alien',
        color: '#10b981',
        sound: { freq: 659, type: 'square', duration: 0.4 },
        audioUrl: '/sounds/alien.wav',
        animation: 'wiggle',
      },
      {
        id: 'ufo',
        emoji: '🛸',
        label: 'UFO',
        color: '#6ee7b7',
        sound: { freq: 784, type: 'triangle', duration: 0.45 },
        audioUrl: '/sounds/ufo.wav',
        animation: 'shake',
      },
      {
        id: 'comet',
        emoji: '☄️',
        label: 'Comet',
        color: '#fcd34d',
        sound: { freq: 440, type: 'sawtooth', duration: 0.3 },
        audioUrl: '/sounds/comet.wav',
        animation: 'spin',
      },
      {
        id: 'astronaut',
        emoji: '👨‍🚀',
        label: 'Astronaut',
        color: '#93c5fd',
        sound: { freq: 587, type: 'sine', duration: 0.5 },
        audioUrl: '/sounds/astronaut.wav',
        animation: 'bounce',
      },
    ],
    slides: [
      {
        id: 'space1',
        bg: 'from-indigo-900 to-purple-900',
        animatedBg: 'linear-gradient(135deg, #1e1b4b, #4c1d95, #312e81, #3730a3, #1e3a8a)',
        title: 'Blast Off!',
        scene: '🚀✨🌟',
        description: '3... 2... 1... Blast off!',
      },
      {
        id: 'space2',
        bg: 'from-blue-900 to-indigo-800',
        animatedBg: 'linear-gradient(135deg, #1e3a8a, #1e1b4b, #0f172a, #312e81, #172554)',
        title: 'The Moon',
        scene: '🌙⭐🌙',
        description: 'Twinkle twinkle little star!',
      },
      {
        id: 'space3',
        bg: 'from-purple-900 to-violet-800',
        animatedBg: 'linear-gradient(135deg, #4a044e, #4c1d95, #6b21a8, #3b0764, #1e1b4b)',
        title: 'Planets',
        scene: '🪐🌍🪐',
        description: 'So many planets to discover!',
      },
      {
        id: 'space4',
        bg: 'from-slate-900 to-blue-900',
        animatedBg: 'linear-gradient(135deg, #0f172a, #1e3a8a, #1e1b4b, #0c4a6e, #172554)',
        title: 'Alien Friends',
        scene: '👾🛸👾',
        description: 'Friendly aliens say hello!',
      },
    ],
  },
  {
    id: 'ocean',
    name: 'Ocean',
    emoji: '🐠',
    bg: 'from-cyan-400 via-blue-400 to-teal-500',
    accent: 'text-blue-900',
    buttonBg: 'bg-blue-500',
    animatedBg: 'linear-gradient(135deg, #22d3ee, #38bdf8, #0e7490, #06b6d4, #0369a1)',
    items: [
      {
        id: 'fish',
        emoji: '🐠',
        label: 'Fish',
        color: '#f97316',
        sound: { freq: 523, type: 'sine', duration: 0.35 },
        audioUrl: '/sounds/fish.wav',
        animation: 'wiggle',
      },
      {
        id: 'whale',
        emoji: '🐳',
        label: 'Whale',
        color: '#0ea5e9',
        sound: { freq: 165, type: 'sine', duration: 0.9 },
        audioUrl: '/sounds/whale.wav',
        animation: 'bounce',
      },
      {
        id: 'octopus',
        emoji: '🐙',
        label: 'Octopus',
        color: '#ec4899',
        sound: { freq: 311, type: 'sine', duration: 0.5 },
        audioUrl: '/sounds/octopus.wav',
        animation: 'shake',
      },
      {
        id: 'crab',
        emoji: '🦀',
        label: 'Crab',
        color: '#ef4444',
        sound: { freq: 415, type: 'triangle', duration: 0.4 },
        audioUrl: '/sounds/crab.wav',
        animation: 'wiggle',
      },
      {
        id: 'dolphin',
        emoji: '🐬',
        label: 'Dolphin',
        color: '#38bdf8',
        sound: { freq: 698, type: 'sine', duration: 0.4 },
        audioUrl: '/sounds/dolphin.wav',
        animation: 'bounce',
      },
      {
        id: 'turtle',
        emoji: '🐢',
        label: 'Turtle',
        color: '#22c55e',
        sound: { freq: 247, type: 'sine', duration: 0.6 },
        audioUrl: '/sounds/turtle.wav',
        animation: 'spin',
      },
      {
        id: 'starfish',
        emoji: '⭐',
        label: 'Starfish',
        color: '#fbbf24',
        sound: { freq: 587, type: 'triangle', duration: 0.3 },
        audioUrl: '/sounds/starfish.wav',
        animation: 'spin',
      },
      {
        id: 'shark',
        emoji: '🦈',
        label: 'Shark',
        color: '#94a3b8',
        sound: { freq: 185, type: 'sawtooth', duration: 0.5 },
        audioUrl: '/sounds/shark.wav',
        animation: 'grow',
      },
    ],
    slides: [
      {
        id: 'ocean1',
        bg: 'from-cyan-500 to-blue-600',
        animatedBg: 'linear-gradient(135deg, #06b6d4, #0284c7, #0e7490, #0369a1, #22d3ee)',
        title: 'Under the Sea',
        scene: '🐠🐡🐟',
        description: 'Colorful fish swim by!',
      },
      {
        id: 'ocean2',
        bg: 'from-blue-500 to-teal-600',
        animatedBg: 'linear-gradient(135deg, #3b82f6, #0d9488, #0284c7, #0f766e, #38bdf8)',
        title: 'Big Whale',
        scene: '🐳💧🐳',
        description: 'The whale splashes big waves!',
      },
      {
        id: 'ocean3',
        bg: 'from-teal-400 to-emerald-600',
        animatedBg: 'linear-gradient(135deg, #2dd4bf, #059669, #0d9488, #34d399, #10b981)',
        title: 'Coral Reef',
        scene: '🐙🦀🐚',
        description: 'Sneaky octopus hides!',
      },
      {
        id: 'ocean4',
        bg: 'from-sky-400 to-blue-500',
        animatedBg: 'linear-gradient(135deg, #38bdf8, #3b82f6, #0ea5e9, #2563eb, #7dd3fc)',
        title: 'Dolphin Play',
        scene: '🐬🌊🐬',
        description: 'Dolphins love to jump!',
      },
    ],
  },
  {
    id: 'fruits',
    name: 'Fruits',
    emoji: '🍓',
    bg: 'from-red-300 via-yellow-200 to-pink-300',
    accent: 'text-red-700',
    buttonBg: 'bg-red-500',
    animatedBg: 'linear-gradient(135deg, #fca5a5, #fde68a, #f9a8d4, #fb923c, #fdba74)',
    items: [
      {
        id: 'strawberry',
        emoji: '🍓',
        label: 'Strawberry',
        color: '#ef4444',
        sound: { freq: 659, type: 'sine', duration: 0.3 },
        audioUrl: '/sounds/strawberry.wav',
        animation: 'bounce',
      },
      {
        id: 'banana',
        emoji: '🍌',
        label: 'Banana',
        color: '#fde047',
        sound: { freq: 523, type: 'sine', duration: 0.35 },
        audioUrl: '/sounds/banana.wav',
        animation: 'wiggle',
      },
      {
        id: 'watermelon',
        emoji: '🍉',
        label: 'Watermelon',
        color: '#86efac',
        sound: { freq: 349, type: 'sine', duration: 0.5 },
        audioUrl: '/sounds/watermelon.wav',
        animation: 'grow',
      },
      {
        id: 'orange',
        emoji: '🍊',
        label: 'Orange',
        color: '#fb923c',
        sound: { freq: 440, type: 'sine', duration: 0.35 },
        audioUrl: '/sounds/orange.wav',
        animation: 'bounce',
      },
      {
        id: 'grapes',
        emoji: '🍇',
        label: 'Grapes',
        color: '#a855f7',
        sound: { freq: 587, type: 'triangle', duration: 0.3 },
        audioUrl: '/sounds/grapes.wav',
        animation: 'shake',
      },
      {
        id: 'pineapple',
        emoji: '🍍',
        label: 'Pineapple',
        color: '#fbbf24',
        sound: { freq: 392, type: 'triangle', duration: 0.4 },
        audioUrl: '/sounds/pineapple.wav',
        animation: 'spin',
      },
      {
        id: 'apple',
        emoji: '🍎',
        label: 'Apple',
        color: '#f87171',
        sound: { freq: 494, type: 'sine', duration: 0.35 },
        audioUrl: '/sounds/apple.wav',
        animation: 'bounce',
      },
      {
        id: 'cherry',
        emoji: '🍒',
        label: 'Cherry',
        color: '#dc2626',
        sound: { freq: 784, type: 'sine', duration: 0.25 },
        audioUrl: '/sounds/cherry.wav',
        animation: 'wiggle',
      },
    ],
    slides: [
      {
        id: 'fruit1',
        bg: 'from-red-300 to-pink-400',
        animatedBg: 'linear-gradient(135deg, #fca5a5, #f9a8d4, #fb7185, #f472b6, #fda4af)',
        title: 'Yummy Berries',
        scene: '🍓🫐🍒',
        description: 'So sweet and yummy!',
      },
      {
        id: 'fruit2',
        bg: 'from-yellow-300 to-orange-400',
        animatedBg: 'linear-gradient(135deg, #fde68a, #fb923c, #fbbf24, #f97316, #fef08a)',
        title: 'Tropical Fun',
        scene: '🍌🍍🥭',
        description: 'Tropical fruits are the best!',
      },
      {
        id: 'fruit3',
        bg: 'from-green-300 to-teal-400',
        animatedBg: 'linear-gradient(135deg, #86efac, #2dd4bf, #4ade80, #34d399, #a7f3d0)',
        title: 'Watermelon Day',
        scene: '🍉🍈🍏',
        description: 'Cool and refreshing!',
      },
      {
        id: 'fruit4',
        bg: 'from-purple-300 to-violet-400',
        animatedBg: 'linear-gradient(135deg, #d8b4fe, #a78bfa, #c084fc, #818cf8, #e879f9)',
        title: 'Fruit Salad',
        scene: '🍇🍑🍊',
        description: 'Mix them all together!',
      },
    ],
  },
  {
    id: 'city',
    name: 'City',
    emoji: '🏙️',
    bg: 'from-slate-300 via-gray-200 to-slate-400',
    accent: 'text-slate-700',
    buttonBg: 'bg-slate-500',
    animatedBg: 'linear-gradient(135deg, #cbd5e1, #e2e8f0, #94a3b8, #f1f5f9, #cbd5e1)',
    items: [
      {
        id: 'skyscraper',
        emoji: '🏢',
        label: 'Skyscraper',
        color: '#bcd0e0',
        sound: { freq: 262, type: 'sine', duration: 0.5 },
        animation: 'grow',
      },
      {
        id: 'house',
        emoji: '🏠',
        label: 'House',
        color: '#f4c9a3',
        sound: { freq: 330, type: 'sine', duration: 0.4 },
        animation: 'bounce',
      },
      {
        id: 'trafficlight',
        emoji: '🚦',
        label: 'Traffic Light',
        color: '#a3e6a3',
        sound: { freq: 523, type: 'square', duration: 0.3 },
        animation: 'shake',
      },
      {
        id: 'taxi',
        emoji: '🚕',
        label: 'Taxi',
        color: '#ffe066',
        sound: { freq: 392, type: 'sawtooth', duration: 0.4 },
        animation: 'wiggle',
      },
      {
        id: 'bus',
        emoji: '🚌',
        label: 'Bus',
        color: '#f4a3a3',
        sound: { freq: 196, type: 'square', duration: 0.5 },
        animation: 'bounce',
      },
      {
        id: 'bridge',
        emoji: '🌉',
        label: 'Bridge',
        color: '#a3c9e6',
        sound: { freq: 294, type: 'sine', duration: 0.6 },
        animation: 'grow',
      },
      {
        id: 'fountain',
        emoji: '⛲',
        label: 'Fountain',
        color: '#b3e0e6',
        sound: { freq: 660, type: 'triangle', duration: 0.5 },
        animation: 'wiggle',
      },
      {
        id: 'shop',
        emoji: '🏪',
        label: 'Shop',
        color: '#c9b3e6',
        sound: { freq: 440, type: 'sine', duration: 0.4 },
        animation: 'spin',
      },
    ],
    slides: [
      {
        id: 'city1',
        bg: 'from-slate-400 to-gray-600',
        animatedBg: 'linear-gradient(135deg, #94a3b8, #64748b, #cbd5e1, #475569, #94a3b8)',
        title: 'The Big City',
        scene: '🏙️🏢🏬',
        description: 'So many tall buildings!',
      },
      {
        id: 'city2',
        bg: 'from-yellow-300 to-orange-400',
        animatedBg: 'linear-gradient(135deg, #fde68a, #fb923c, #fbbf24, #f97316, #fef08a)',
        title: 'Busy Streets',
        scene: '🚕🚌🚦',
        description: 'Cars and buses everywhere!',
      },
      {
        id: 'city3',
        bg: 'from-cyan-300 to-blue-400',
        animatedBg: 'linear-gradient(135deg, #67e8f9, #60a5fa, #22d3ee, #3b82f6, #a5f3fc)',
        title: 'By the Bridge',
        scene: '🌉⛲🌆',
        description: 'The bridge crosses the river.',
      },
      {
        id: 'city4',
        bg: 'from-purple-300 to-indigo-400',
        animatedBg: 'linear-gradient(135deg, #d8b4fe, #818cf8, #c084fc, #6366f1, #e879f9)',
        title: 'City Lights',
        scene: '🌃🏙️✨',
        description: 'The city shines at night!',
      },
    ],
  },
  {
    id: 'park',
    name: 'Park',
    emoji: '🌳',
    bg: 'from-green-300 via-lime-200 to-emerald-400',
    accent: 'text-emerald-700',
    buttonBg: 'bg-emerald-500',
    animatedBg: 'linear-gradient(135deg, #86efac, #bef264, #6ee7b7, #a3e635, #a7f3d0)',
    items: [
      {
        id: 'tree',
        emoji: '🌳',
        label: 'Tree',
        color: '#a3d9a3',
        sound: { freq: 220, type: 'sine', duration: 0.6 },
        animation: 'grow',
      },
      {
        id: 'flower',
        emoji: '🌸',
        label: 'Flower',
        color: '#ffc2dd',
        sound: { freq: 660, type: 'triangle', duration: 0.4 },
        animation: 'wiggle',
      },
      {
        id: 'bench',
        emoji: '🪑',
        label: 'Bench',
        color: '#d4a574',
        sound: { freq: 294, type: 'sine', duration: 0.4 },
        animation: 'bounce',
      },
      {
        id: 'playground',
        emoji: '🛝',
        label: 'Slide',
        color: '#ffd699',
        sound: { freq: 523, type: 'square', duration: 0.4 },
        animation: 'spin',
      },
      {
        id: 'parkduck',
        emoji: '🦆',
        label: 'Duck',
        color: '#fff3b0',
        sound: { freq: 440, type: 'sawtooth', duration: 0.4 },
        animation: 'shake',
      },
      {
        id: 'squirrel',
        emoji: '🐿️',
        label: 'Squirrel',
        color: '#d9a066',
        sound: { freq: 587, type: 'triangle', duration: 0.3 },
        animation: 'bounce',
      },
      {
        id: 'butterfly',
        emoji: '🦋',
        label: 'Butterfly',
        color: '#b3d9ff',
        sound: { freq: 784, type: 'sine', duration: 0.4 },
        animation: 'wiggle',
      },
      {
        id: 'parkfountain',
        emoji: '⛲',
        label: 'Fountain',
        color: '#b3e0e6',
        sound: { freq: 698, type: 'triangle', duration: 0.5 },
        animation: 'grow',
      },
    ],
    slides: [
      {
        id: 'park1',
        bg: 'from-green-400 to-emerald-600',
        animatedBg: 'linear-gradient(135deg, #4ade80, #059669, #86efac, #10b981, #6ee7b7)',
        title: 'In the Park',
        scene: '🌳🌸🦋',
        description: 'A lovely day in the park!',
      },
      {
        id: 'park2',
        bg: 'from-lime-300 to-green-400',
        animatedBg: 'linear-gradient(135deg, #bef264, #4ade80, #a3e635, #22c55e, #d9f99d)',
        title: 'Playtime',
        scene: '🛝🪑🌼',
        description: 'Time to play and have fun!',
      },
      {
        id: 'park3',
        bg: 'from-cyan-300 to-teal-400',
        animatedBg: 'linear-gradient(135deg, #67e8f9, #2dd4bf, #22d3ee, #14b8a6, #a5f3fc)',
        title: 'By the Pond',
        scene: '🦆⛲🌿',
        description: 'Ducks swim in the pond.',
      },
      {
        id: 'park4',
        bg: 'from-amber-300 to-orange-400',
        animatedBg: 'linear-gradient(135deg, #fcd34d, #fb923c, #fbbf24, #f97316, #fde68a)',
        title: 'Little Friends',
        scene: '🐿️🦋🌳',
        description: 'Animals love the park too!',
      },
    ],
  },
  {
    id: 'planes',
    name: 'Planes',
    emoji: '✈️',
    bg: 'from-sky-300 via-blue-200 to-cyan-400',
    accent: 'text-sky-700',
    buttonBg: 'bg-sky-500',
    animatedBg: 'linear-gradient(135deg, #7dd3fc, #bfdbfe, #38bdf8, #93c5fd, #a5f3fc)',
    items: [
      {
        id: 'airplane',
        emoji: '✈️',
        label: 'Airplane',
        color: '#bcd9f0',
        sound: { freq: 196, type: 'sawtooth', duration: 0.6 },
        animation: 'bounce',
      },
      {
        id: 'helicopter',
        emoji: '🚁',
        label: 'Helicopter',
        color: '#f4a3a3',
        sound: { freq: 147, type: 'square', duration: 0.6 },
        animation: 'spin',
      },
      {
        id: 'balloon',
        emoji: '🎈',
        label: 'Hot Air Balloon',
        color: '#ffb3b3',
        sound: { freq: 523, type: 'sine', duration: 0.5 },
        animation: 'grow',
      },
      {
        id: 'parachute',
        emoji: '🪂',
        label: 'Parachute',
        color: '#ffd699',
        sound: { freq: 440, type: 'triangle', duration: 0.5 },
        animation: 'wiggle',
      },
      {
        id: 'jet',
        emoji: '🛩️',
        label: 'Jet',
        color: '#c9d9e6',
        sound: { freq: 233, type: 'sawtooth', duration: 0.5 },
        animation: 'shake',
      },
      {
        id: 'rocket',
        emoji: '🚀',
        label: 'Rocket',
        color: '#d9b3ff',
        sound: { freq: 110, type: 'sawtooth', duration: 0.7 },
        animation: 'bounce',
      },
      {
        id: 'kite',
        emoji: '🪁',
        label: 'Kite',
        color: '#a3e6d9',
        sound: { freq: 659, type: 'triangle', duration: 0.4 },
        animation: 'wiggle',
      },
      {
        id: 'cloud',
        emoji: '☁️',
        label: 'Cloud',
        color: '#e6f0f7',
        sound: { freq: 349, type: 'sine', duration: 0.5 },
        animation: 'grow',
      },
    ],
    slides: [
      {
        id: 'plane1',
        bg: 'from-sky-400 to-blue-600',
        animatedBg: 'linear-gradient(135deg, #38bdf8, #2563eb, #7dd3fc, #3b82f6, #93c5fd)',
        title: 'Up in the Sky',
        scene: '✈️☁️🌤️',
        description: 'Flying high above the clouds!',
      },
      {
        id: 'plane2',
        bg: 'from-cyan-300 to-sky-400',
        animatedBg: 'linear-gradient(135deg, #67e8f9, #38bdf8, #22d3ee, #0ea5e9, #a5f3fc)',
        title: 'Whirly Helicopter',
        scene: '🚁☁️🏞️',
        description: 'The helicopter spins its blades!',
      },
      {
        id: 'plane3',
        bg: 'from-orange-300 to-red-400',
        animatedBg: 'linear-gradient(135deg, #fdba74, #f87171, #fb923c, #ef4444, #fed7aa)',
        title: 'Balloon Ride',
        scene: '🎈🪂🌅',
        description: 'Floating gently in the air!',
      },
      {
        id: 'plane4',
        bg: 'from-indigo-400 to-purple-600',
        animatedBg: 'linear-gradient(135deg, #818cf8, #9333ea, #a5b4fc, #7e22ce, #c4b5fd)',
        title: 'Blast Off!',
        scene: '🚀🌙⭐',
        description: 'The rocket zooms into space!',
      },
    ],
  },
  {
    id: 'vehicles',
    name: 'Vehicles',
    emoji: '🚗',
    bg: 'from-red-300 via-orange-200 to-amber-400',
    accent: 'text-red-700',
    buttonBg: 'bg-red-500',
    animatedBg: 'linear-gradient(135deg, #fca5a5, #fed7aa, #fb923c, #fbbf24, #fecaca)',
    items: [
      {
        id: 'car',
        emoji: '🚗',
        label: 'Car',
        color: '#f4a3a3',
        sound: { freq: 220, type: 'sawtooth', duration: 0.4 },
        animation: 'bounce',
      },
      {
        id: 'truck',
        emoji: '🚚',
        label: 'Truck',
        color: '#a3c9e6',
        sound: { freq: 147, type: 'square', duration: 0.6 },
        animation: 'shake',
      },
      {
        id: 'tractor',
        emoji: '🚜',
        label: 'Tractor',
        color: '#9ccc65',
        sound: { freq: 110, type: 'square', duration: 0.6 },
        animation: 'wiggle',
      },
      {
        id: 'motorcycle',
        emoji: '🏍️',
        label: 'Motorcycle',
        color: '#d9b3ff',
        sound: { freq: 165, type: 'sawtooth', duration: 0.5 },
        animation: 'shake',
      },
      {
        id: 'train',
        emoji: '🚂',
        label: 'Train',
        color: '#d4a574',
        sound: { freq: 131, type: 'square', duration: 0.7 },
        animation: 'bounce',
      },
      {
        id: 'bicycle',
        emoji: '🚲',
        label: 'Bicycle',
        color: '#a3e6d9',
        sound: { freq: 523, type: 'triangle', duration: 0.3 },
        animation: 'spin',
      },
      {
        id: 'digger',
        emoji: '🚙',
        label: 'Jeep',
        color: '#ffd699',
        sound: { freq: 196, type: 'sawtooth', duration: 0.5 },
        animation: 'bounce',
      },
      {
        id: 'ambulance',
        emoji: '🚑',
        label: 'Ambulance',
        color: '#fff0f0',
        sound: { freq: 587, type: 'square', duration: 0.5 },
        animation: 'wiggle',
      },
    ],
    slides: [
      {
        id: 'vehicle1',
        bg: 'from-red-400 to-orange-600',
        animatedBg: 'linear-gradient(135deg, #f87171, #ea580c, #fb923c, #dc2626, #fed7aa)',
        title: 'Vroom Vroom!',
        scene: '🚗🚚🏍️',
        description: 'So many things that go!',
      },
      {
        id: 'vehicle2',
        bg: 'from-green-300 to-lime-400',
        animatedBg: 'linear-gradient(135deg, #86efac, #a3e635, #4ade80, #84cc16, #d9f99d)',
        title: 'On the Farm',
        scene: '🚜🌾🚙',
        description: 'The tractor works the fields.',
      },
      {
        id: 'vehicle3',
        bg: 'from-blue-300 to-indigo-400',
        animatedBg: 'linear-gradient(135deg, #93c5fd, #818cf8, #60a5fa, #6366f1, #bfdbfe)',
        title: 'All Aboard!',
        scene: '🚂🚃🚉',
        description: 'The train chugs down the track!',
      },
      {
        id: 'vehicle4',
        bg: 'from-rose-300 to-red-400',
        animatedBg: 'linear-gradient(135deg, #fda4af, #f87171, #fb7185, #ef4444, #fecdd3)',
        title: 'To the Rescue',
        scene: '🚑🚒🚓',
        description: 'Beep beep! Help is coming!',
      },
    ],
  },
  {
    id: 'ships',
    name: 'Ships',
    emoji: '🚢',
    bg: 'from-blue-300 via-cyan-200 to-teal-400',
    accent: 'text-blue-700',
    buttonBg: 'bg-blue-500',
    animatedBg: 'linear-gradient(135deg, #93c5fd, #a5f3fc, #60a5fa, #2dd4bf, #bfdbfe)',
    items: [
      {
        id: 'ship',
        emoji: '🚢',
        label: 'Ship',
        color: '#a3c9e6',
        sound: { freq: 110, type: 'sine', duration: 0.7 },
        animation: 'bounce',
      },
      {
        id: 'sailboat',
        emoji: '⛵',
        label: 'Sailboat',
        color: '#e6f0f7',
        sound: { freq: 294, type: 'sine', duration: 0.5 },
        animation: 'wiggle',
      },
      {
        id: 'speedboat',
        emoji: '🚤',
        label: 'Speedboat',
        color: '#a3e6e6',
        sound: { freq: 196, type: 'sawtooth', duration: 0.4 },
        animation: 'shake',
      },
      {
        id: 'ferry',
        emoji: '⛴️',
        label: 'Ferry',
        color: '#b3d9ff',
        sound: { freq: 147, type: 'square', duration: 0.6 },
        animation: 'bounce',
      },
      {
        id: 'anchor',
        emoji: '⚓',
        label: 'Anchor',
        color: '#c9d9e6',
        sound: { freq: 165, type: 'sine', duration: 0.5 },
        animation: 'grow',
      },
      {
        id: 'submarine',
        emoji: '🛟',
        label: 'Life Ring',
        color: '#ffb3b3',
        sound: { freq: 392, type: 'triangle', duration: 0.4 },
        animation: 'spin',
      },
      {
        id: 'lighthouse',
        emoji: '🗼',
        label: 'Lighthouse',
        color: '#ffd699',
        sound: { freq: 523, type: 'sine', duration: 0.5 },
        animation: 'grow',
      },
      {
        id: 'canoe',
        emoji: '🛶',
        label: 'Canoe',
        color: '#d4a574',
        sound: { freq: 330, type: 'sine', duration: 0.4 },
        animation: 'wiggle',
      },
    ],
    slides: [
      {
        id: 'ship1',
        bg: 'from-blue-400 to-cyan-600',
        animatedBg: 'linear-gradient(135deg, #60a5fa, #0891b2, #93c5fd, #06b6d4, #a5f3fc)',
        title: 'Out at Sea',
        scene: '🚢🌊⚓',
        description: 'Sailing across the big ocean!',
      },
      {
        id: 'ship2',
        bg: 'from-cyan-300 to-teal-400',
        animatedBg: 'linear-gradient(135deg, #67e8f9, #2dd4bf, #22d3ee, #14b8a6, #a5f3fc)',
        title: 'Sail Away',
        scene: '⛵🌤️🐚',
        description: 'The wind fills the sails!',
      },
      {
        id: 'ship3',
        bg: 'from-amber-300 to-orange-400',
        animatedBg: 'linear-gradient(135deg, #fcd34d, #fb923c, #fbbf24, #f97316, #fde68a)',
        title: 'The Lighthouse',
        scene: '🗼🌅🌊',
        description: 'The lighthouse guides the ships.',
      },
      {
        id: 'ship4',
        bg: 'from-teal-300 to-blue-400',
        animatedBg: 'linear-gradient(135deg, #5eead4, #60a5fa, #2dd4bf, #3b82f6, #99f6e4)',
        title: 'Little Boats',
        scene: '🚤🛶⛴️',
        description: 'Boats of every kind!',
      },
    ],
  },
]
